#!/bin/sh
# Create an initial CRL
CRL="crl.pem"
if [ "$KEY_DIR" ]; then
    cd "$KEY_DIR"
    # set defaults
    export KEY_CN=""
    export KEY_OU=""
    export KEY_NAME=""
    # generate a new CRL
    $OPENSSL ca -gencrl -crldays "$CRL_EXPIRE" -out "$CRL" -config "$KEY_CONFIG"
else
    echo 'Please source the vars script first (i.e. "source ./vars")'
    echo 'Make sure you have edited it to reflect your configuration.'
fi
